### ISSUE TITLE
Safety of OAuth credentials

### ISSUE THREAD

**Issue by felipeborges** [dracarys09/gcp-backend#11]
I wouldn't expose the API tokens/keys in https://github.com/dracarys09/gcp-backend/blob/master/backend/gcp.h#L9

**Comment by dracarys09** [comment]
@felipeborges that means access_token and refresh_token should be pvt members... and they should be accessed by set and get methods ?

**Comment by felipeborges** [comment]
@dracarys09 yes.

**Comment by dracarys09** [comment]
@felipeborges now we can close this one right ?

**Comment by felipeborges** [comment]
@dracarys09 sure. Thank you.
