### ISSUE TITLE
Implement backend interface and DBus related methods

### ISSUE THREAD

**Issue by dracarys09** [dracarys09/gcp-backend#32]

**Comment by dracarys09** [comment]
@felipeborges I've implemented DBus related stuff... However I need your help as I'm not able to modify makefile appropriately and my code is not compiling... Basically, there is a file called ```gcp_server.c``` this file has a main method which obtains dbus connection, connect to signals etc... There is another file called ```test.c``` this file creates a proxy object and calls GCP related methods over DBus

Both of these files need to have a main function, and I'm getting multiple declaration of main error... I need your help in linking these files properly.

**Comment by dracarys09** [comment]
@felipeborges I've committed all the changes, please run ```make``` to reproduce the error I'm getting

**Comment by felipeborges** [comment]
1. You cannot have multiple instances of the mainloop in your context.
2. Make gcp_server a GObject and run acquire_session_bus_name () in the _init method.
